#!/bin/sh
# -*- sh -*-
#
# Redistribution and use in source and binary forms, 
# with or without modification, are permitted provided 
# that the following conditions are met:
#
# 1. Redistributions of source code must retain the above 
# copyright notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the 
# above copyright notice, this list of conditions and 
# the following disclaimer in the documentation and/or 
# other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY Claudiu Vasadi ``AS IS'' 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
# SHALL Claudiu Vasadi OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and 
# documentation are those of the authors and should not be
# interpreted as representing official policies, either 
# expressed or implied, of Claudiu Vasadi.
#
#
# Plugin to graph apache's status codes from the access log
#
# Date: 21.10.2013
# Author: Claudiu Vasadi
#
# requires:
# [apache_status_codes]
# user root
#
# Magick markers (optional):
#%# family=legacy
#%# capabilities=autoconf

apache_file="/var/log/access-log"

# autoconf (quick and very dirty)
if [ "$1" = "autoconf" ]; then
        echo "yes"
        exit 0
fi

# config
if [ "$1" = "config" ]; then
        echo 'graph_title Apache status codes'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel Total number'
        echo 'graph_category apache'
        echo 'graph_info This graph shows the number of apache status codes'

for i in `cat $apache_file | awk '{print ($(NF-3))}' \
  | grep -o '^[0-9][0-9][0-9]$' | sort | uniq`;do
     echo "\
HTTP_$i.label HTTP_$i
HTTP_$i.info apache status code
HTTP_$i.type GAUGE"
done
exit 0
fi

# data section
cat $apache_file | awk '{print ($(NF-3))}' | grep -o '^[0-9][0-9][0-9]$' | \
  sort | uniq -c | \
    awk '{print "HTTP_"$2".value "$1}'